const LOGIN = 'LOGIN';
const REGISTER = 'REGISTER';
const HOME = 'HOME';
const RESET_PASSWORD = 'RESET_PASSWORD';
const CANDIDATES = 'CANDIDATES'

export {LOGIN, REGISTER, HOME, RESET_PASSWORD, CANDIDATES};