const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT'
const CANDIDATE_DETAILS = 'CANDIDATE_DETAILS'
const VOTE = 'VOTE'
const CLOSE_POSITION = 'CLOSE_POSITION'


export {LOGIN, LOGOUT, CANDIDATE_DETAILS, VOTE, CLOSE_POSITION};